	<link rel="stylesheet" href="css/jq.css" type="text/css" />
	<link rel="stylesheet" href="css/style.css" type="text/css" />
	<link rel="stylesheet" href="css/hover.css" type="text/css" />
	<script type="text/javascript" src="JS/jquery.js"></script>
	<script type="text/javascript" src="JS/jquery.tablesorter.js">
	</script>
	
		<link rel="stylesheet" href="css/hover.css" type="text/css">
		
	<script type="text/javascript">
	$(document).ready(function(){ 
    $("#tablesorted").tablesorter({headers:{3:{sorter: false},4:{sorter: false},6:{sorter: false},7:{sorter: false},12:{sorter: false},17:{sorter: false}} 
    }); });
	</script>
	
