	
	<link rel="stylesheet" href="css/jq.css" type="text/css" />
	<link rel="stylesheet" href="css/style.css" type="text/css" />
	<script type="text/javascript" src="JS/jquery.js"></script>
	<script type="text/javascript" src="JS/jquery.tablesorter.js">
	</script>
	
		<link rel="stylesheet" href="css/hover.css" type="text/css">
		<link rel="stylesheet" href="css/results.css" type="text/css">
	<script type="text/javascript">
	$(document).ready(function(){ 
    $("#tablesorted").tablesorter({headers:{2:{sorter: false},3:{sorter: false},4:{sorter: false},5:{sorter: false}} 
    }); });
	</script>